include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false;
    positional_after_named_argument: false;
    missing_identifier: false;
    

analyzer:
  exclude:
    - lib/app/models/personal_info/personal_info.g.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - dart_code_metrics
  errors:
      invalid_annotation_target: ignore



# dart_code_metrics:
#   metrics:
#     cyclomatic-complexity: 20
#     number-of-arguments: 4
#     maximum-nesting-level: 5
#   metrics-exclude:
#     - test/**
#   rules:
#     - newline-before-return
#     - no-boolean-literal-compare
#     - prefer-trailing-comma
#     - prefer-conditional-expressions
#     - no-equal-then-else
#   anti-patterns:
#     - long-method
#     - long-parameter-list


  
