name: chaseapp
description: Never miss a live police chase again

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more credits Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more credits iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
publish_to: 'none' 

version: 1.2.2+9b

#  2.12.0 nonnullable
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  shared_preferences: ^2.0.11
  cloud_firestore: ^3.1.5
  firebase_messaging: ^11.2.4
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.2.0
  firebase_database: ^9.0.4
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  flutter_spinkit: ^5.1.0
  google_sign_in: ^5.2.1
  launch_review: ^3.0.1
  fluttertoast: ^8.0.8
  cached_network_image: ^3.1.0+1
  image_picker: ^0.8.4+4
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.16
  http: ^0.13.4
  path_provider: ^2.0.7
  # provider: ^6.0.1
  # get_it: ^7.2.0
  flutter_progress_hud: ^2.0.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  permission_handler:
    git:
      url: https://github.com/Baseflow/flutter-permission-handler.git
      path: permission_handler/
    
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  algolia: ^1.0.4
  flutter_svg: ^1.0.0
  youtube_player_flutter: ^8.0.0
  lottie: ^1.2.1
  share_plus: ^3.0.4
  dotted_border: ^2.0.0+2
  flutter_local_notifications: ^9.1.5
  freezed_annotation:
  json_annotation:
  flutter_riverpod: ^1.0.3
  firebase_dynamic_links: ^4.0.4
  sign_in_with_apple: ^3.3.0
  flutter_facebook_auth: ^3.5.0
  twitter_login: ^4.0.1
  firebase_crashlytics: ^2.5.0
  logging: ^1.0.2
  device_preview: ^1.0.0
  audioplayers: ^0.20.1
  connectivity_plus: ^2.2.0
  firebase_remote_config: ^2.0.0
  package_info_plus: ^1.3.0
  linkable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # For configuring launcher icons
  flutter_launcher_icons: ^0.9.2  
  # For analytics  
  analyzer: ^2.8.0
  dart_code_metrics: ^4.8.0
  very_good_analysis: ^2.4.0
  # For Freeze/Code generation
  freezed: 
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/
    - assets/icon/
    - assets/audio/
    - images/donut.png
    - images/sparkles.png
    - images/chaseapp.png
    - images/broadcast.png
    - images/video.png
    - images/google_logo.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Crawl
      fonts:
        - asset: assets/fonts/crawl_regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
