name: chaseapp
description: Never miss a live police chase again

# The following defines the version and build number for your application
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more credits Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more credits iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
publish_to: "none"

version: 1.5.4+92

#  2.12.0 nonnullable
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # Firebase
  firebase_messaging: 14.0.3
  firebase_analytics: 10.0.3
  firebase_auth: 4.1.0
  cloud_firestore: 4.0.4
  cloud_functions: 4.0.3
  firebase_database: 10.0.3
  firebase_core: 2.1.1
  firebase_storage: 11.0.3
  firebase_remote_config: 3.0.3
  firebase_crashlytics: 3.0.3
  firebase_dynamic_links: 5.0.3

  # Social Auth
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^3.3.0
  flutter_facebook_auth: ^3.5.0
  twitter_login: ^4.2.2

  # State Management
  flutter_riverpod: ^1.0.3

  # Networking
  http: ^0.13.4
  connectivity_plus: ^2.2.0
  linkable: ^3.0.1
  url_launcher: ^6.0.16

  # # Search
  # algolia: ^1.0.4

  #Chat
  stream_chat_flutter: 5.0.1

  # Device specific
  path_provider: ^2.0.7
  package_info_plus: ^1.3.0
  share_plus: ^4.5.0
  # flutter_local_notifications: ^9.1.5
  shared_preferences: ^2.0.11

  # Permissions
  permission_handler:
    git:
      url: https://github.com/Baseflow/flutter-permission-handler.git
      path: permission_handler/

  # Logging
  logging: ^1.0.2

  # Media
  audioplayers: ^0.20.1
  # youtube_player_flutter: ^8.0.0

  youtube_player_flutter:
    # path: youtube_player_flutter/packages/youtube_player_flutter/
    git:
      url: https://github.com/rutvik110/youtube_player_flutter.git
      path: packages/youtube_player_flutter/

  # UI/Animations/Assets
  # flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.0
  # lottie: ^1.2.1
  launch_review: ^3.0.1
  cached_network_image: ^3.1.0+1
  google_fonts: ^2.1.0
  # carousel_slider: ^4.0.0

  # Pusher
  pusher_beams:
    ^1.1.1
    # git:
    #   url: https://github.com/chase-app/push-notifications-flutter.git
    #   path: packages/pusher_beams
  pusher_channels_flutter: ^2.0.2

  # social_embed_webview: ^0.3.2
  webview_flutter: ^2.8.0
  rive: ^0.8.1

  # Stream
  stream_feed_flutter_core: ^0.7.0+1

  # Testing
  mapbox_gl: 0.16.0
  # platform_maps_flutter: ^1.0.2
  collection: ^1.16.0
  umbra_flutter: ^0.1.0-dev.4
  path: ^1.8.2

dependency_overrides:
  # firebase_core_platform_interface: 4.5.1
  # firebase_core_platform_interface: 4.4.3
  # video_compress: 3.1.0
  video_compress:
    git:
      url: https://github.com/jonataslaw/VideoCompress.git
      ref: master
  # cloud_functions_platform_interface: 5.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: 0.9.0
  google_sign_in_mocks: ^0.2.1
  fake_cloud_firestore: 2.0.1
  integration_test:
    sdk: flutter
  # Configuring launcher icons
  flutter_launcher_icons: ^0.9.2
  # Analytics
  analyzer:
  # Code Generation
  json_annotation:
  dart_code_metrics: ^4.21.2
  very_good_analysis: ^2.4.0
  # Freeze/Code generation
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0
  build_runner:
  json_serializable: ^6.5.1

  # Dev tools

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/
    - assets/icon/
    - assets/audio/
    - assets/rive/
    - images/donut.png
    - images/sparkles.png
    - images/chaseapp.png
    - images/broadcast.png
    - images/video.png
    - images/google_logo.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Crawl
      fonts:
        - asset: assets/fonts/crawl_regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
