// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBWaNlpwRap3EJRfpLi2hK30ITsmJSXje4',
//     appId: '1:1020122644146:android:995de4171ddbeaadcc13ab',
//     messagingSenderId: '1020122644146',
//     projectId: 'chaseapp-8459b',
//     databaseURL: 'https://chaseapp-8459b.firebaseio.com',
//     storageBucket: 'chaseapp-8459b.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC9k8oblmrTpSc8vam5dI-q_9sdm31X1zA',
//     appId: '1:1020122644146:ios:a47350134259d189',
//     messagingSenderId: '1020122644146',
//     projectId: 'chaseapp-8459b',
//     databaseURL: 'https://chaseapp-8459b.firebaseio.com',
//     storageBucket: 'chaseapp-8459b.appspot.com',
//     androidClientId: '1020122644146-dl90vmeld8jr6am1onbd84oqekqg64sl.apps.googleusercontent.com',
//     iosClientId: '1020122644146-b8ma1mtle6ic9rlunfb0vm2kdhhp427t.apps.googleusercontent.com',
//     iosBundleId: 'com.carverauto.chaseapp',
//   );
// }
