# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

pod 'GoogleUtilities/AppDelegateSwizzler'
pod 'GoogleUtilities/MethodSwizzler'
pod 'GoogleUtilities/Network'
pod 'GoogleUtilities/NSData+zlib'
pod 'GoogleUtilities/AppDelegateSwizzler'
pod 'GoogleUtilities/Environment'
pod 'GoogleUtilities/Logger'
pod 'GoogleUtilities/UserDefaults'
pod 'GoogleUtilities/Reachability'


# # Pusher
# pod 'PushNotifications'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  # use_modular_headers!

  # pod 'NodleSDK'
  pod 'SQLite.swift', '~> 0.13.2'
  pod 'SwiftCBOR', '~> 0.4.4'
  pod 'SwiftProtobuf', '~> 1.18.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      # Start - Enabling permissions
      # Enabling permissions here is required as per new updates on permission_handler plugin
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',
       
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',  
        
        ## dart: PermissionGroup.bluetooth
        # 'PERMISSION_BLUETOOTH=0',
    ]
    # End
    end
  end
end

target 'AppImageNotification' do
  use_frameworks!
  pod 'Firebase/Messaging'
end
