#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keepattributes Signature
-keepclassmembers class com.carverautomation.chaseapp.models.** { *; }
-keep class com.firebase.** { *; }
-dontwarn com.fasterxml.**
-optimizations !class/merging/*
