name: Flutter CI (Android)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: echo $KEY_JKS > key.jks
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter build apk -v --flavor prod --target lib/main_prod.dart
      - uses: actions/upload-artifact@v1
        with:
          name: app-prod-release
          path: build\app\outputs\flutter-apk\app-prod-release.apk